### ISSUE TITLE
[question] using just cpu (no gpu)?

### ISSUE THREAD

**Issue by jarlva** [danijar/dreamer#15]
Hi,
I have a windows 10 pc and a ubuntu 18.04 pc, both without GPU. Can it run on them?

**Comment by danijar** [comment]
Yes, that's possible. Just comment out any `with tf.device()` parts in the code. It would be too slow for training from images, but could be fine for [training from low-dim inputs](https://github.com/danijar/dreamer/issues/16).

**Comment by jarlva** [comment]
Thanks for the replies @danijar.
I hope this technology will continue to evolve and mature.
