### ISSUE TITLE
Have you meet value function explosion when developing?

### ISSUE THREAD

**Issue by IcarusWizard** [danijar/dreamer#20]
Hi Danijar. Yet another question about the actor-critic part.

I am trying to use the actor-critic part in my own project with a different world model. Sometimes the whole model works fine, but sometimes the value function suddenly explodes exponentially. I use the same gradient clip as you, but it did not stop the explosion. I wonder if you have meet the same phenomena when developing. Anything would be helpful. Thanks in advance.

**Comment by danijar** [comment]
Hi, thanks for your question. Yes, the value function can be a bit unstable and gradient clipping is a simple solution that usually works. If it doesn't, you can simply use a slow target network. Updating it every 100 gradient steps works well. I've been using that for some exploration objectives that change throughout learning. I'll also add a flag for this to the repository at some point, probably when I have more time after upcoming the NeurIPS deadline.
