### ISSUE TITLE
Question about preprocess for observation

### ISSUE THREAD

**Issue by cross32768** [danijar/dreamer#21]
Hello.
I have a question about preprocess for observation in Dreamer.
In the [PlaNet implementation](https://github.com/google-research/planet), preprocess function converts images to 5-bits and adds noise, but it looks that preprocess function in this repository doesn't do such preprocess. Did you find that such preprocess is unnecessary for Dreamer?

**Comment by danijar** [comment]
Exactly. We found that this preprocessing wasn't necessary for PlaNet either. We just used it at the time because it was common in other generative modeling codebases.
