### ISSUE TITLE
Reconciling Fig 3a with code.

### ISSUE THREAD

**Issue by zafarali** [danijar/dreamer#22]
Hi Danijar,

Thanks for releasing this tf2 implementation! 

I was curious about how to reconcile the lines here:
https://github.com/danijar/dreamer/blob/1e38b1d80e11335883108720e671d35cc34de96e/dreamer.py#L159-L163

with the figure 
![image](https://user-images.githubusercontent.com/6295292/82970325-5650b380-9f9e-11ea-92b4-7c10614ba55e.png)

In particular, the figure shows that the reconstruction observation (o_hat_1) is made from the rssm state obtained from encoding the true image (o_hat). However, the code above seems to suggest that the reconstruction is created by doing a single step of the RRSM?

Can you clarify how to reconcile these two things?

Thanks,

**Comment by danijar** [comment]
The image is reconstructed from the state at the current time step, so it is not a forward prediction. The `RSSM.observe()` function integrates the previous state, previous action, and current CNN features into the current state that is returned.
