### ISSUE TITLE
Add flag for slow target value function

### ISSUE THREAD

**Issue by AliengirlLiv** [danijar/dreamer#30]
In [this issue](https://github.com/danijar/dreamer/issues/20), you mentioned that using a slow target network for the value function could prevent the loss from diverging.  Would it be possible to add a flag to enable this option?  Or could you please describe how you implemented this feature? Thanks!

**Comment by danijar** [comment]
This is implemented in the DreamerV2 repository: https://github.com/danijar/dreamerv2
