### ISSUE TITLE
Dreamer for DMLab

### ISSUE THREAD

**Issue by syigzaw** [danijar/dreamer#34]
I'm not sure if you're still working on this, but if you are, I was wondering why the implementation here doesn't support DMLab environments. The older implementation does, but I'd rather not use have to use the older dependencies it relies on. Are you planning on adding this, or do I have to go with the older implementation on google-research?

**Comment by danijar** [comment]
Hey, I'm planning on adding this but I don't have a clear timeline for it yet.
