### ISSUE TITLE
Performance on sparse reward

### ISSUE THREAD

**Issue by E666GT** [danijar/dreamer#35]
Hi Danijar,
Great work in dreamer. I have a question, do you think the Dreamer will perform well upon extremely sparse reward problem? Like only a reward is gotten at the very last step.

Thanks

**Comment by abrandenb** [comment]
Hi,
if I'm not mistaken, Dreamer has been applied on the "ball-in-cup" task from the DM control suite (for the task description, you can [look here](https://arxiv.org/pdf/1801.00690.pdf) - just search for "cup"). I do not know, however if the episode is terminated on success, you would need to check that if you think it is important. 
You can see the performance in the [Dreamer paper](https://arxiv.org/pdf/1912.01603.pdf) - in my eyes it seems that it performs quite well. 

Best,
André

**Comment by danijar** [comment]
There are a lot more things that play into how well it works than weather the reward is only given at the last time step. Because there is a value function, it could work. The easiest way to find out is to run an experiment.
