### ISSUE TITLE
A question about reward and observation pairing in wrapper

### ISSUE THREAD

**Issue by FinnWeng** [danijar/dreamer#36]
Thank you for providing this great works! 

I have a question about the reward and observation paring in wrapper. For my understanding, the ```transition``` of  function ```step``` of class ```Collect``` at line 164 in wrappers.py is corresponding to ob{t}, reward{t-1}, action{t-1}. Since the Line 162 ```obs, reward, done, info = self._env.step(action)``` shows the action and reward are at same {t}, and obs is at {t+1}.
And when using this transition for updating model in function ```_train``` of class ```Dreamer```, the reward{t-1} is the target of ```reward_pred```, which is from state{t}, rooting from ob{t}, state{t-1} and action{t-1} . 

But according to definition of reward model: q(r_t | s_t), the target of ```reward_pred``` should be reward{t}. So the ```transition``` should store the ob{t} reward{t} and action{t-1}. Am I misrecognizing the reward in ```transition``` as reward{t-1}?

**Comment by danijar** [comment]
The transitions are stored as tuples `(a_t-1, x_t, r_t)`.

**Comment by FinnWeng** [comment]
Thank you for answering!
