### ISSUE TITLE
Tensorflow-probability version

### ISSUE THREAD

**Issue by eugenevinitsky** [danijar/dreamer#38]
Hi Danijar,

The setup instructions do not contain a pointer to the right tensorflow-probability version. It's probably not the case that bugs are induced by new versions but just in case, do you know the version you used?

Thanks!

**Comment by wrightr-AIS** [comment]
I ran into the same issues and was able to get things running with tensorflow-probability==0.8.0

Here is a full list from pip in my conda env:
Package                Version
---------------------- -------------------
absl-py                0.11.0
astor                  0.8.1
atari-py               0.2.6
cached-property        1.5.2
cachetools             4.1.1
certifi                2020.6.20
chardet                3.0.4
cloudpickle            1.1.1
cycler                 0.10.0
decorator              4.4.2
dm-control             0.0.322773188
dm-env                 1.3
dm-tree                0.1.5
ffmpeg                 1.4
future                 0.18.2
gast                   0.2.2
glfw                   2.0.0
google-auth            1.23.0
google-auth-oauthlib   0.4.2
google-pasta           0.2.0
grpcio                 1.33.2
gym                    0.17.3
h5py                   3.1.0
idna                   2.10
importlib-metadata     2.0.0
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
kiwisolver             1.3.1
labmaze                1.0.3
lxml                   4.6.1
Markdown               3.3.3
matplotlib             3.3.3
numpy                  1.19.4
oauthlib               3.1.0
opencv-python          4.4.0.46
opt-einsum             3.3.0
pandas                 1.1.4
Pillow                 8.0.1
pip                    20.2.4
protobuf               3.14.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pyglet                 1.5.0
PyOpenGL               3.1.5
pyparsing              2.4.7
python-dateutil        2.8.1
pytz                   2020.4
requests               2.25.0
requests-oauthlib      1.3.0
rsa                    4.6
scipy                  1.4.1
setuptools             50.3.1.post20201107
six                    1.15.0
tensorboard            2.1.1
tensorflow-estimator   2.1.0
tensorflow-gpu         2.1.0
tensorflow-probability 0.8.0
termcolor              1.1.0
tqdm                   4.52.0
urllib3                1.26.2
Werkzeug               1.0.1
wheel                  0.35.1
wrapt                  1.12.1
zipp                   3.4.0

**Comment by eugenevinitsky** [comment]
Thanks! It also works with 0.9.0 so I just worry there might be bugs in between tf-probability versions since silent breaking changes between versions happens ALL THE TIME with tensorflow
