### ISSUE TITLE
lost of file 'dm_control'

### ISSUE THREAD

**Issue by yueyue-yue** [danijar/dreamer#40]

**Comment by yueyue-yue** [comment]
located at 
.../dream/wrappers.py", line 19, in __init__
    from dm_control import suite

**Comment by danijar** [comment]
It's a dependency: https://github.com/deepmind/dm_control

**Comment by yueyue-yue** [comment]
Thank you!!!!!!! It really help me!!!!😭
________________________________
发件人: Danijar Hafner <notifications@github.com>
发送时间: 2021年1月18日 14:19
收件人: danijar/dreamer <dreamer@noreply.github.com>
抄送: Yue Zenglin <e0575902@u.nus.edu>; Author <author@noreply.github.com>
主题: Re: [danijar/dreamer] lost of file 'dm_control' (#40)

        - External Email -



Closed #40<https://github.com/danijar/dreamer/issues/40>.
