### ISSUE TITLE
difference between "CheetahRun-v0" on DM vs "half-cheetah-v2" on Mujuco

### ISSUE THREAD

**Issue by randyhouse** [danijar/dreamer#41]
What is the difference between "CheetahRun-v0" on DM vs "half-cheetah-v2" on Mujuco?

From what I can tell, do they only differ by the reward functions?
Both environments output action as 6 dimensions.

**Comment by danijar** [comment]
Sorry, this is not the right place to discuss environment details that are independent of this code base and the corresponding paper. I hope you'll be able to find an answer to your question.
