### ISSUE TITLE
Spikes in Loss?

### ISSUE THREAD

**Issue by mctigger** [danijar/dreamer#42]
Hi everyone,
I reimplemented Dreamer in PyTorch. When running I see some kind of loss spikes. I was wondering if that is something that you also experience or whether this is a problem of my implementation:

50k batches / 500k env steps:

![kl-divergence](https://user-images.githubusercontent.com/4086336/109650283-484b4700-7b5d-11eb-8568-47f06b4f6bd8.png)

**Comment by danijar** [comment]
Hi, cool that you implemented it in PyTorch. I don't think I've seen any spikes like that so it's quite likely to be a bug somewhere.

**Comment by mctigger** [comment]
Thank you for answering so quickly! 

Interestingly the spikes seem to not influence my results, but I still try to find the reason and then report back.

For now the issue can be closed.
