### ISSUE TITLE
Runtime performance

### ISSUE THREAD

**Issue by mctigger** [danijar/dreamer#43]
Hi Danijar,
I have a question regarding the runtime performance. Is the implementation here the same as in the paper with ~3 hours per 1 million steps? Also run in eager mode?

My PyTorch implementation takes ~9 hours on an RTX3090 (which should be comparable to a V100), however the implementation here is similarly fast as my own implementation when tested on a GTX1080TI.

**Comment by danijar** [comment]
It will be much slower in eager mode. The is a `--debug` flag that enables eager mode for simple debugging but for longer experiments, this should be disabled so the expensive functions are JIT compiled. For MuJoCo tasks with default hyper parameters and mixed precision `(--precision 16`), I get about 90 environment steps per second on a V100 GPU with the implementation here.
