### ISSUE TITLE
Free nats over batch and time dimension?

### ISSUE THREAD

**Issue by mctigger** [danijar/dreamer#44]
Hi again,
regarding these lines:
https://github.com/danijar/dreamer/blob/2d58db947b05ef1fba57dbc18cd7c2b774136ee5/dreamer.py#L174-L175

Does this mean the loss is averaged into a scalar first and then the max with the free nats is applied? This is different than described here:
https://github.com/google-research/planet/issues/28#issuecomment-488268661
So did this change between PlaNet and Dreamer or did I understand something wrong?

**Comment by danijar** [comment]
Yes, that changed between the two papers. Averaging first gives the model more freedom in how to distribute its free nats across time steps.
