### ISSUE TITLE
How to run on short episodes?

### ISSUE THREAD

**Issue by mctigger** [danijar/dreamer#47]
Hello Danijar,
how can I run this code on environments like https://gym.openai.com/envs/InvertedPendulum-v2/ in which the early episodes tend to be very short (5-10 steps)?

Best,
Tim

**Comment by danijar** [comment]
You could set the batch size to `(50, 5)` to train on very short sequences. I don't know if it'll work.

**Comment by mctigger** [comment]
Okay, thanks I will try that!
