### ISSUE TITLE
slow in atari tasks

### ISSUE THREAD

**Issue by xiangyyyy** [danijar/dreamer#48]
I'm running Atari tasks on the nvidia 2080 and A100 respectively, but I only have around 20 FPS, which is too slow.
That means it takes tens of days to run 10 million steps. When you run the Atari task, how much time does each task take?
Is there a way to speed things up?

{"step": 1446778, "expl_amount": 0.09999962151050568, "model_grad_norm": 12.273571968078613, "value_grad_norm": 2023.7537841796875, "actor_grad_norm": 367.6117248535156, "prior_ent": 73.4467544555664, "post_ent": 70.40204620361328, "image_loss": 11264.0, "reward_loss": 1.7543749809265137, "pcont_loss": 0.5491357445716858, "div": 3.099745988845825, "model_loss": 11264.7998046875, "value_loss": Infinity, "actor_loss": -190.18875122070312, "action_ent": 0.013957500457763672, "fps": 20.45536337258022}

**Comment by xiangyyyy** [comment]
my command is  the  same as  #33
python dreamer.py --logdir ./logdir/atari_mspacman/dreamer/2 --task atari_ms_pacman --expl epsilon_greedy --horizon 10 --kl_scale 0.1 --action_dist onehot --expl_amount 0.4 --expl_min 0.1 --expl_decay 100000 --pcont True --time_limit 1000000

**Comment by danijar** [comment]
Hi, please use the [DreamerV2 code base](https://github.com/danijar/dreamerv2) for Atari experiments.
