### ISSUE TITLE
Questions about RSSM

### ISSUE THREAD

**Issue by danijar** [danijar/dreamer#5]
From @xlnwel (asked in #4):

Also, I try to reframe RSSM so that I can wrap it with `tf.keras.layers.RNN`. Here's the cell structure I come up with

<img width="307" alt="image" src="https://user-images.githubusercontent.com/10184153/76273268-6e2a6c80-62b8-11ea-9c07-93f5cddaa730.png">

where $e_t$ is the embedding and $s'_t$ is the output of the posterior. Here, I move the deterministic and stochastic state models into a single RSSM cell and compute the posterior after the RNN is expanded. I humbly think this structure may be faster as we can process all posterior at once after the RNN is expanded. However, I'm not sure if I miss something. Do you think this structure is consistent with your implementation?

After implementing my version of RSSM, I found that I misunderstood it before: RSSM is expanded differently at dynamics learning and behavior learning. I think the correct diagram should be the following one

<img width="668" alt="Screen Shot 2020-03-11 at 23 10 41" src="https://user-images.githubusercontent.com/10184153/76432199-9bc50200-63ed-11ea-8851-038ac7e2c036.png">

At the time of dynamics learning, the hidden state is computed from the output of the posterior $q$(the left part) while during the imagine phase, the hidden state is computed from the output of the prior $p$(the right part). I can see that the left matches the VAE structure. However, I can't explain why it should be preferred compared to the one I previously considered. Could you help me clarify it?

**Comment by danijar** [comment]
Check out the [PlaNet paper](https://arxiv.org/pdf/1811.04551.pdf) where we introduced this model, especially Figure 2c. You are right that the prior and posterior transitions differ. Specifically, the prior does not have access to the embedding of the image. This allows predicting ahead without knowing the images. In the figure I pointed you to, the solid lines are always used but the dashed lines are only used by the posterior. I don't think your diagrams are correct, or I don't quite understand them. I would draw them as

```
Prior:               Posterior: 
                       
a ---.               a ---. 
     |                    | 
     |                    | 
h ---+---> h'        h ---+---> h'  
     |     |              |     |  
     |     v              |     v  
s ---'     s'        s ---'     s'  
                                ^
                                |
                                o'
```

**Comment by xlnwel** [comment]
Hi @danijar,

Sorry that I misplaced the some of notations in the diagrams and left the previous issue unorganized. 

Here's a figure I draw about the RSSM

<img width="683" alt="image" src="https://user-images.githubusercontent.com/10184153/76684820-0d00f100-664a-11ea-9a56-eb0186638655.png">

The left part shows how the RSSM looks like in a single time step when we call `RSSM.observe`([this line](https://github.com/danijar/dreamer/blob/02f0210f5991c7710826ca7881f19c64a012290c/dreamer.py#L160)), where $e$ is the image embedding, $s'$ is the posterior state, and $s$ is the prior state. The right part shows how the RSSM looks like when we call `dreamer._imagine_ahead`([this line](https://github.com/danijar/dreamer/blob/02f0210f5991c7710826ca7881f19c64a012290c/dreamer.py#L180)). My point, if I understand them right, is that the GRU takes $s'$ from the posterior as input when we call `RSSM.observe`. In contrast, when we call `dreamer._imagine_ahead`, the GRU takes $s$ from the prior as input. This different behavior confused me for a while. Then I realized that when we compute the KL divergence in the ELBO, we take the expectation under the posterior. Furthermore, the dynamics model is trained using the data collected by the policy, which is conditioned on the feature from the posterior. Both make sense of the left diagram. 

Hope these can help you understand the figure I drew. Of course, if I made some mistakes, please let me know.

**Comment by danijar** [comment]
Yes, you can think of the prior as a loose guess about the next state and of the posterior as a more precise guess, because it is based on additional evidence, namely the observed image.

During training images are available and the GRU takes a posterior sample as input. During imagination, the future images are not available and the GRU takes a prior sample as input instead.

Intuitively, this works because the posterior and prior are trained to be close to each other using the KL regularizer. And because the random samples have some spread during training, the GRU becomes robust to seeing new samples during imagination.

Mathematically, you are right that this simply follows from the evidence lower bound.

When interacting with the environment, the current image is available, and so we use the posterior.
