### ISSUE TITLE
AttributeError: 'MirroredStrategy' object has no attribute 'experimental_run_v2'

### ISSUE THREAD

**Issue by lylyjy** [danijar/dreamer#50]
@tf.function()
  def train(self, data, log_images=False):
    # strategy.run
    self._strategy.experimental_run_v2(self._train, args=(data, log_images))

**Comment by danijar** [comment]
You're using a newer version of TF than is listed in the readme. The method is called `run()` now.

That said, I highly recommend giving [DreamerV2](github.com/danijar/dreamerv2) a try. The code base also supports Gaussian latents with a flag.
