### ISSUE TITLE
the code is running without any results and output

### ISSUE THREAD

**Issue by lylyjy** [danijar/dreamer#51]
Hi,
When I run dreamer.py, it only outputs the following documents:

Prefill dataset with 5000 steps.
Train episode of length 1000 with return 38.9.
Train episode of length 1000 with return 50.6.
Train episode of length 1000 with return 46.3.
Train episode of length 1000 with return 43.8.
Train episode of length 1000 with return 44.6.
Simulating agent for 4995000 steps.
Found 5296820 model parameters.
Found 578412 actor parameters.
Found 413601 value parameters.
Start evaluation.
Training for 100 steps.

And it seems that the code is running without any results and output, do you know how to solve it? Thanks.

**Comment by lylyjy** [comment]
while step < config.steps:
    print('Start evaluation.')
    tools.simulate(
        functools.partial(agent, training=False), test_envs, episodes=1)

it seems that the code is running here, and it can't stop and output anything.

**Comment by danijar** [comment]
It seems like it's running as intended. What are you expecting to see?

**Comment by lylyjy** [comment]
I want to debug the following code, but it seems that there will be a long time to finish this line:
while step < config.steps:
     print('Start evaluation.')
     tools.simulate(functools.partial(agent, training=False), test_envs, episodes=1)

So can I know how long it will take? Thanks.

**Comment by IcarusWizard** [comment]
I think I have seen it before. Check if your GPU is correctly used (with some Volatile GPU-Util).

**Comment by danijar** [comment]
Right, maybe you're not using a GPU or your environment is very slow. If you switch to [DreamerV2](github.com/danijar/dreamerv2), you can also verify that the code is running correctly by using `--configs defaults atari debug`. The `debug` config will reduce the batch size and increase the logging frequency.
