### ISSUE TITLE
freenats inconsistent with tf1 repo

### ISSUE THREAD

**Issue by ssnl** [danijar/dreamer#53]
Hi! I've read this issue (https://github.com/danijar/dreamer/issues/44) but the original tf1 dreamer repo seems to cap the per-timestep KL before averaging:
https://github.com/google-research/dreamer/blob/d517542f9777c53864ff6f2683cea88be9ea98ac/dreamer/training/utility.py#L160-L163
https://github.com/google-research/dreamer/blob/d517542f9777c53864ff6f2683cea88be9ea98ac/dreamer/training/utility.py#L240

Should that be capping after averaging instead (as done in this repo)? Or maybe I am missing something?

Thanks in advance!

**Comment by danijar** [comment]
Either is fine, it's an algorithmic choice. I don't know which one is better.
