### ISSUE TITLE
Can't reproduce results in some environments

### ISSUE THREAD

**Issue by zplizzi** [danijar/dreamer#54]
I'm having trouble reproducing the results you achieved (in the paper and in `scores/dreamer.json`) for some environments, using the code in this repository. `cartpole_swingup_sparse` is one of the environments that most clearly doesn't reproduce, so I'll show examples of it here. I'm just running 1M steps as this environment approximately plateaus in your scores in this time frame.

In `dreamer.json`, the scores for this env look like: 

![image](https://user-images.githubusercontent.com/5598968/157911644-f5a30349-db44-44df-8f25-f1bd79d415c0.png)

And in the paper, the scores look like (interestingly decently different than `scores.json`):

![image](https://user-images.githubusercontent.com/5598968/157911388-8fd077be-ea5e-4076-b2a3-1826ff3b6fbc.png)

Both reach 700-800 by 1M steps.

I'm running this command: `rm -rf logdir/test && CUDA_VISIBLE_DEVICES=0 python3 dreamer.py --logdir ./logdir/test --task dmc_cartpole_swingup_sparse --steps 1e6`.

First, I tried it with modern versions of all the packages (easier to set up than old packages). Tensorflow 2.5.0, CUDA 11.3, dm-control 0.0.425341097, A100 GPU, etc. I changed one line of code from `experimental_run_v2` to `run`, but otherwise the code ran fine. 

Then, I figured that maybe the reproduction issues were due to differences in package versions, so I tried to create an environment as close as possible to what you might have used (with a clean checkout of this repository):
- python 3.8.10
- tensorflow 2.2.0
- tf probability [0.10.0](https://github.com/tensorflow/probability/releases/tag/v0.10.0)
    - cloudpickle 1.3 required to get this working
- dm_control commit 5701a00df44b84197692199794ad15cd1d2d0d55 from jan 27, 2020.
- mujoco 2.0.0
- gym [0.17.1 ](https://github.com/openai/gym/releases/tag/0.17.1) from march 2020. 
- PIL [7.1.0 ](https://github.com/python-pillow/Pillow/releases/tag/7.1.0) from april 2020
- numpy==1.19.5
- cuda 10.1
- cudnn 7.6.5
- one V100 GPU

However, I'm still not able to get results that are close to yours. Here's some tensorboard graphs. Dark blue is from the "modern" environment, and red and light blue are from the env that is hopefully close to yours. I've run other replicates and they look similar to these - none look anything like the ones in `dreamer.json`.

![image](https://user-images.githubusercontent.com/5598968/157912873-a17cdc36-d370-44b7-abcf-81b80db3468f.png)
![image](https://user-images.githubusercontent.com/5598968/157912920-c7a750e0-f70d-4e8f-9a96-0a123366db12.png)

Let me know what I might be doing wrong here! Happy to provide the full log files. If you have a list of exactly the packages you used I can try running again with those. I've been trying to release a clean Pytorch port of this repository (none of the existing ones really work too well), and my implementation seems to match the results of this code but is also unable to match the results in `dreamer.json`.

**Comment by danijar** [comment]
Hi, the paper experiments all used the [previous implementation](https://github.com/google-research/dreamer) and there are slight performance differences with this code base (in general the performance is a bit better).

**Comment by zplizzi** [comment]
@danijar are the scores in `scores/dreamer.json` from the old implementation or from this implementation? Because they don't match what I get when I run this code.

**Comment by danijar** [comment]
To be honest, I don't remember 100% but I'm fairly sure they are from this implementation, just slightly earlier hyper parameters. Also see: https://github.com/danijar/dreamer/issues/55. Hope that helps!
