### ISSUE TITLE
Provided scores don't match the results

### ISSUE THREAD

**Issue by zhixuan-lin** [danijar/dreamer#55]
Hello, 

Thanks for the code! Just want to confirm, are the scores in [`dreamer.json`](https://github.com/danijar/dreamer/blob/56d4d444dfd0582b0e79dab80aebbea74c0ce40d/scores/dreamer.json) from the old implementation or this TF2 implementation? This was asked [before](https://github.com/danijar/dreamer/issues/54#issuecomment-1068262942) but not yet answered (and I also encounter the same reproducibility issue for Pendulum Swingup).

**Comment by zhixuan-lin** [comment]
![Screen Shot 2022-04-22 at 12 21 49 PM](https://user-images.githubusercontent.com/32564447/164755238-d9ca4938-5298-4e64-a82e-5604850dee68.png)
The line `Dreamer` comes from `dreamer.json` and `Dreamer-TF2` is the results I got by running the code in this repo, averaged over 3 seeds.

**Comment by danijar** [comment]
Hi, the scores are from the same code base but with an earlier hyper parameter setting. The new hyper parameters work better in general but on this task learning slowed down a little bit. Either way, I would recommend to run [DreamerV2](https://github.com/danijar/dreamerv2). Hope that helps!
