### ISSUE TITLE
Maybe a shift in action sequence?

### ISSUE THREAD

**Issue by IcarusWizard** [danijar/dreamer#8]
Hi @danijar ,

Thanks for sharing your great work. I have a question about the action sequence. In the paper, the  posterior distribution of s_t is defined as p(s_t | s_{t-1}, a_{t-1}, o_t}. But in function `observe` of `RSSM`, action and embed are passed to `obs_step` with the same index. So we may actually compute p(s_t | s_{t-1}, a_t, o_t}. I am confused by this shift. Therefore, I am afraid that I understand the code wrong. Please let me know if I made any mistakes.

Best regards,

**Comment by danijar** [comment]
Did you check the `Collect` environment wrapper in `wrappers.py`?

**Comment by IcarusWizard** [comment]
So, the action is stored in a shifted manner, got it! I will close the issue.
